version: '3.2'

services:

## migration containers to populate data 
  keto-migrate1:
    image: oryd/keto:latest
    links:
      - postgresd1:postgresd1
    volumes:
      - type: bind
        source: ./config
        target: /home/ory
    environment:
      - LOG_LEVEL=debug
      - DSN=postgres://dbuser:secret@postgresd1:5432/accesscontroldb?sslmode=disable
    command: ['migrate', 'up', '-y']
    restart: on-failure

  keto-migrate2:
    image: oryd/keto:latest
    links:
      - postgresd2:postgresd2
    volumes:
      - type: bind
        source: ./config
        target: /home/ory
    environment:
      - LOG_LEVEL=debug
      - DSN=postgres://dbuser:secret@postgresd2:5432/accesscontroldb?sslmode=disable
    command: ['migrate', 'up', '-y']
    restart: on-failure

  keto-migrate3:
    image: oryd/keto:latest
    links:
      - postgresd3:postgresd3
    volumes:
      - type: bind
        source: ./config
        target: /home/ory
    environment:
      - LOG_LEVEL=debug
      - DSN=postgres://dbuser:secret@postgresd3:5432/accesscontroldb?sslmode=disable
    command: ['migrate', 'up', '-y']
    restart: on-failure

  keto-migrate4:
    image: oryd/keto:latest
    links:
      - postgresd4:postgresd4
    volumes:
      - type: bind
        source: ./config
        target: /home/ory
    environment:
      - LOG_LEVEL=debug
      - DSN=postgres://dbuser:secret@postgresd4:5432/accesscontroldb?sslmode=disable
    command: ['migrate', 'up', '-y']
    restart: on-failure
  
  
## Keto Clients  
## ports are 44$6 (on the machine) : 4466 // $ stands for node id
## ports are 44$7 (on the machine) : 4467 // $ stands for node id
## ports are 44$8 (on the machine) : 4468 // $ stands for node id

  keto1:
    build:
      context: '.'
      dockerfile: '.docker/Dockerfile-build'
    ports:
      - '4416:4466'
      - '4417:4467'
      - '4418:4468'
    command: serve -c /home/ory/keto.yml
    restart: on-failure
    volumes:
      - type: bind
        source: './config'
        target: '/home/ory'
    environment:
      - LOG_LEVEL=debug
      - PORT=4466
      - DSN=postgres://dbuser:secret@postgresd1:5432/accesscontroldb?sslmode=disable
    image: oryd/keto:latest
    links:
      - postgresd1:postgresd1
    depends_on:
      - keto-migrate1

  keto2:
    build:
      context: '.'
      dockerfile: '.docker/Dockerfile-build'
    ports:
      - '4426:4466'
      - '4427:4467'
      - '4428:4468'
    command: serve -c /home/ory/keto.yml
    restart: on-failure
    volumes:
      - type: bind
        source: './config'
        target: '/home/ory'
    environment:
      - LOG_LEVEL=debug
      - PORT=4466
      - DSN=postgres://dbuser:secret@postgresd2:5432/accesscontroldb?sslmode=disable
    image: oryd/keto:latest
    links:
      - postgresd2:postgresd2
    depends_on:
      - keto-migrate2

  keto3:
    build:
      context: '.'
      dockerfile: '.docker/Dockerfile-build'
    ports:
      - '4436:4466'
      - '4437:4467'
      - '4438:4468'
    command: serve -c /home/ory/keto.yml
    restart: on-failure
    volumes:
      - type: bind
        source: './config'
        target: '/home/ory'
    environment:
      - LOG_LEVEL=debug
      - PORT=4466
      - DSN=postgres://dbuser:secret@postgresd3:5432/accesscontroldb?sslmode=disable
    image: oryd/keto:latest
    links:
      - postgresd3:postgresd3
    depends_on:
      - keto-migrate3

  keto4:
    build:
      context: '.'
      dockerfile: '.docker/Dockerfile-build'
    ports:
      - '4446:4466'
      - '4447:4467'
      - '4448:4468'
    command: serve -c /home/ory/keto.yml
    restart: on-failure
    volumes:
      - type: bind
        source: './config'
        target: '/home/ory'
    environment:
      - LOG_LEVEL=debug
      - PORT=4466
      - DSN=postgres://dbuser:secret@postgresd4:5432/accesscontroldb?sslmode=disable
    image: oryd/keto:latest
    links:
      - postgresd2:postgresd2
    depends_on:
      - keto-migrate4


## database containers
## ports are 543$ (on the machine) : 5432 // $ stands for node id

  postgresd1:
    image: postgres:9.6
    ports:
      - '5431:5432'
    environment:
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=accesscontroldb

  postgresd2:
    image: postgres:9.6
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=accesscontroldb

  postgresd3:
    image: postgres:9.6
    ports:
      - '5433:5432'
    environment:
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=accesscontroldb

  postgresd4:
    image: postgres:9.6
    ports:
      - '5434:5432'
    environment:
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=accesscontroldb


## Redis cachce
  redis:
      image: redis:6.2-alpine
      ports:
        - 6379:6379
      command: redis-server --save 60 1 --loglevel debug

###### Instructions on how to use
## after changing code
# 1. make docker          this recompiles with the new code a creates a new local keto docker immage
# 2. docker-compose -f docker-compose-stack.yml down            ensure the previous stack that was deploy is fully down
# 3. docker-compose -f docker-compose-stack.yml up --remove-orphans    deploy the setup that results with the whole infrastructure up and running


## information
# keto instances
## read ports are 44$6 (on the machine) : 4466 // $ stands for node id
## write ports are 44$7 (on the machine) : 4467 // $ stands for node id
# postgres instances 
## ports are 543$ (on the machine) : 5432 // $ stands for node id