version: "3.2"

services:
  keto:
    image: oryd/keto:v25.4.0
    working_dir: /home/ory
    ports:
      - "4466:4466"
      - "4467:4467"
    command: serve -c keto.yml
    restart: on-failure
    volumes:
      - type: bind
        source: .
        target: /home/ory

  keto-init:
    image: oryd/keto:v25.4.0
    working_dir: /home/ory
    environment:
      - KETO_WRITE_REMOTE=keto:4467
    volumes:
      - type: bind
        source: .
        target: /home/ory
    command:
      relation-tuple create
      ./relation-tuples  --insecure-disable-transport-security
    restart: on-failure
